title: Other
nav:
  - index.md
  - PDFs: pdf.md
  - EKGF: https://ekgf.org
  - Manifesto: https://manifesto.ekgf.org
  - Maturity Model: https://maturity-model.ekgf.org
  - Use Case Tree Method: https://use-case-tree-method.ekgf.org
  - contributors.md
  - author
  - ...
