title: Other
nav:
  - index.md
  - PDFs: pdf.md
  - EKGF: https://ekgf.org
  - Principles: https://principles.ekgf.org
  - Maturity: https://maturity.ekgf.org
  - Method: https://method.ekgf.org
  - Catalog: https://catalog.ekgf.org
  - contributors.md
  - ...
