= EKG/MM

This repository contains the link:https://www.latex-project.org/about/[LaTeX]
based source documents of EKG/MM, the Maturity Model for the EKG.

== License

image:https://img.shields.io/github/license/EKGF/ekg-mm.svg[link="http://creativecommons.org/licenses/by-sa/4.0/"]

This work is licensed under a
link:http://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 International License].

== Where is this published?

From this git repository we generate a PDF document.
Two in fact: the "editors-version" which contains annotations and "todo's" and the "release-version" without those annotations.

You can find the published version at https://ekgf.org/maturitymodel.

For members of the EKGF there's also a Slack channel called
link:https://ekgf.slack.com/archives/C01TEL6GWEN[#ekg-mm-latest]
where both PDFs are published every time someone pushes
a change into this repository.

NOTE: Soon we'll also be publishing this content as HTML.

== Where to find the content?

The "raw" LaTeX source documents (see LaTeX below for an explanation) can be
found in the link:ekg-mm[/ekg-mm] directory and more specifically in the
link:ekg-mm/sections[/ekg-mm/sections] directory.

== LaTeX

link:https://www.latex-project.org/about/[LaTeX], which is pronounced «Lah-tech»
or «Lay-tech» (to rhyme with «blech» or «Bertolt Brecht»), is a document
preparation system for high-quality typesetting.
It is most often used for medium-to-large technical or scientific documents
but it can be used for almost any form of publishing.

LaTeX is not a word processor! Instead, LaTeX encourages authors not to worry
too much about the appearance of their documents but to concentrate on getting
the right content.

NOTE: See also https://www.latex-project.org/about/

== Github

This repository resides on Github as https://github.com/EKGF/ekg-mm.

=== How to clone?

For advanced users who often contribute to this repository, it's best to
create a so-called `git clone` of this git repository on the local drive which
allows any given LaTeX editor to be used locally to create new content.

First, install git and/or Github Desktop.

How to create a clone of the github repo:

[source]
----
cd ~ # go to your home directory or the directory where you want your git clones to be
git clone https://github.com/EKGF/ekg-mm
cd ekg-mm
./latex-lib/install-as-subtree.sh
----

== Create PDFs

Various PDF documents are generated from the content in this repository.

=== Prerequisites

* Docker for Mac or Docker for Windows
* PDF viewer that can automatically reload the generated document so that you can keep the PDF viewer open in another window
** use Preview.app on Mac
** or install Skim (download https://skim-app.sourceforge.io/[here])

=== Docker

* From project root, run:

* The `./build-all.sh` command will build all documents using your local Docker installation.
 It can take a long time. Use the `./build.sh` command to build individual documents.
* The docker image is several GBs large so it will take time to download the first time.
 It will be cached on your machine's docker registry.
* The PDF files will be generated and stored in the link:./out[./out] directory.

=== LaTeX compiler

==== Mac OS X

On Mac OS X install LaTeX as follows:

----
brew install --cask mactex-no-gui # see https://formulae.brew.sh/cask/mactex-no-gui
sudo tlmgr texdoc # used by IntelliJ editor and other editors for documentation of packages
sudo tlmgr update --self
sudo tlmgr update --all
----

== Editors

Any text editor will do. Edit the `.tex` files in this repository, they're just
ASCII files.

=== IntelliJ Idea / CLion

* IntelliJ has by far the best "git merge" options of any tool out there,if you're planning to write a lot of content
 then it makes sense to install the "community edition" (free) and get used to IntelliJ.
* https://github.com/Hannah-Sten/TeXiFy-IDEA[TeXiFy Intellij plugin] - allow you to compile the document just like
 it's a source code of any programming language.

== Build steps

To construct the PDF from all the various LaTex documents in this repository we use
the `latexmk` command which is bundled with your LaTeX installation.

To launch the default PDF viewer after each "build" if you run the `latexmk` command
with the `-pvc` option:

For instance, for the `release-version` of EKGF's `ekg-mm` document:

[source]
----
latex_document_mode=release-version latex_document_main=ekg-mm latex_customer_code=ekgf latexmk -gg -pvc
----

The value for the variable `latex_document_main` must be one of the top level
directories in this repository such as `ekg-mm` or `ekg-manifesto`.

The value for the variable `latex_document_mode` is either `editors-version` or `release-version`.

To generate a document with different styling you could use any of the names under
the directory `customer-assets` such as `ekgf`.

It is recommended to install the Adobe Acrobat Reader or preferably Skim since
those PDF viewers support automatic refresh when you generated a new version of
the document.
