name: Create PDF
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        env:
          OSFONTDIR: ${GITHUB_WORKSPACE}/etc/fonts
        with:
          root_file: ekg-mm/ekg-mm.tex
          latexmk_use_lualatex: true