name: Create PDF
on: [push]

jobs:
  create-pdf:
    strategy:
      matrix:
        customer: [ 'ekgf', 'agnos-ai' ]
        mode: [ 'draft', 'final' ]
        members_only: [ 'yes', 'no' ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        env:
          TERM: 'xterm-256color'
          OSFONTDIR: ${GITHUB_WORKSPACE}/etc/fonts
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          latex_document_main: 'content/main.tex'
          latex_customer_code: ${{ matrix.customer }}
          latex_document_mode: ${{ matrix.mode }}
          latex_document_members_only: ${{ matrix.members_only }}
        with:
          root_file: content/main.tex
          latexmk_use_lualatex: true
          extra_system_packages: ncurses
      - name: Store Members Only PDF
        if: ${{ matrix.members_only == 'yes' && matrix.customer == 'ekgf' }}
        uses: actions/upload-artifact@v2
        with:
          name: 'members-only'
          path: './out/*-members-only*.pdf'
      - name: Store PDF with agnos.ai logo
        if: ${{ matrix.customer == 'agnos-ai' }}
        uses: actions/upload-artifact@v2
        with:
          name: 'agnos.ai'
          path: './out/agnos-*.pdf'


