name: Create PDF
on: [push]

jobs:
  create-pdf:
    strategy:
      matrix:
        customer: [ 'ekgf', 'agnos-ai' ]
        mode: [ 'draft', 'final' ]
        members_only: [ 'yes', 'no' ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        env:
          OSFONTDIR: ${GITHUB_WORKSPACE}/etc/fonts
          latex_document_customer: ${{ matrix.customer }}
          latex_document_mode: ${{ matrix.mode }}
          latex_document_members_only: ${{ matrix.members_only }}
        with:
          root_file: ekg-mm/ekg-mm.tex
          latexmk_use_lualatex: true
          extra_system_packages: ncurses
      - name: Store PDF
        uses: actions/upload-artifact@v2
        with:
          path: './out/*.pdf'


