name: docs
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v2
    -
      uses: actions/cache@v2
      with:
        key: ${{ github.ref }}
        path: .cache
    -
      run: |
        pip install --upgrade mkdocs
        pip install --upgrade mkdocs-material
        pip install --upgrade mkdocs-localsearch
        pip install --upgrade mdx-spanner
        pip install --upgrade mkdocs-awesome-pages-plugin
        pip install --upgrade mkdocs-macros-plugin
    -
      run: mkdocs gh-deploy --force
