name: docs
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v2
    -
      uses: actions/cache@v2
      with:
        key: ${{ github.ref }}
        path: .cache
    -
      run: pip install mkdocs-material
    -
      run: mkdocs gh-deploy --force
