name: Build Website

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  website:
    runs-on: macos-12
    steps:
      -
        name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.4'
      -
        uses: actions/cache@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          key: ${{ github.ref }}
          path: .cache
      -
        name: Install all MkDocs dependencies
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          PAT_MKDOCS_INSIDERS: ${{ secrets.PAT_MKDOCS_INSIDERS }}
        run: make --environment-overrides docs-install-python-packages
      -
        name: Build Site
        if: ${{ github.ref != 'refs/heads/main' }}
        env:
          PAT_MKDOCS_INSIDERS: ${{ secrets.PAT_MKDOCS_INSIDERS }}
        run: make --environment-overrides docs-build
      -
        name: Deploy Site
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          PAT_MKDOCS_INSIDERS: ${{ secrets.PAT_MKDOCS_INSIDERS }}
        run: make --environment-overrides docs-deploy
